import SwiftUI

struct Theme: Identifiable, Equatable, Hashable {
    let id: String
    let name: String
    let isDark: Bool
    
    // Editor Colors
    let editorBackground: Color
    let editorForeground: Color
    let selection: Color
    let cursor: Color
    let lineNumber: Color
    let lineNumberActive: Color
    let currentLineHighlight: Color
    let bracketPair1: Color
    let bracketPair2: Color
    let bracketPair3: Color
    let bracketPair4: Color
    let bracketPair5: Color
    let bracketPair6: Color
    let indentGuide: Color
    let indentGuideActive: Color
    
    // UI Colors
    let sidebarBackground: Color
    let sidebarForeground: Color
    let sidebarSectionHeader: Color
    let sidebarSelection: Color
    let activityBarBackground: Color
    let activityBarForeground: Color
    let activityBarSelection: Color
    let tabBarBackground: Color
    let tabActiveBackground: Color
    let tabInactiveBackground: Color
    let tabActiveForeground: Color
    let tabInactiveForeground: Color
    let statusBarBackground: Color
    let statusBarForeground: Color
    
    // Syntax Colors
    let keyword: Color
    let string: Color
    let number: Color
    let comment: Color
    let function: Color
    let type: Color
    let variable: Color
    
    // Semantic Colors
    let errorForeground: Color
    let warningForeground: Color
    let successForeground: Color
    let infoForeground: Color
    let errorBackground: Color
    let warningBackground: Color
    let successBackground: Color
    
    // UI Chrome
    let border: Color
    let activeBorder: Color
    let overlayColor: Color
    let disabledForeground: Color
    
    // Diff Colors
    let diffAddedBackground: Color
    let diffRemovedBackground: Color
    let diffHeaderBackground: Color
    
    // MARK: - VS Code Default Themes
    
    static let darkPlus = Theme(
        id: "dark_plus",
        name: "Dark+ (Default Dark)",
        isDark: true,
        editorBackground: Color(hex: "#1E1E1E"),
        editorForeground: Color(hex: "#D4D4D4"),
        selection: Color(hex: "#264F78"),
        cursor: Color(hex: "#AEAFAD"),
        lineNumber: Color(hex: "#858585"),
        lineNumberActive: Color(hex: "#C6C6C6"),
        currentLineHighlight: Color(hex: "#FFFFFF").opacity(0.1),
        bracketPair1: Color(hex: "#FFD700"),
        bracketPair2: Color(hex: "#DA70D6"),
        bracketPair3: Color(hex: "#179FFF"),
        bracketPair4: Color(hex: "#FFD700"),
        bracketPair5: Color(hex: "#DA70D6"),
        bracketPair6: Color(hex: "#179FFF"),
        indentGuide: Color(hex: "#404040"),
        indentGuideActive: Color(hex: "#707070"),
        sidebarBackground: Color(hex: "#252526"),
        sidebarForeground: Color(hex: "#CCCCCC"),
        sidebarSectionHeader: Color(hex: "#383838"),
        sidebarSelection: Color(hex: "#37373D"),
        activityBarBackground: Color(hex: "#333333"),
        activityBarForeground: Color(hex: "#FFFFFF"),
        activityBarSelection: Color(hex: "#FFFFFF"),
        tabBarBackground: Color(hex: "#252526"),
        tabActiveBackground: Color(hex: "#1E1E1E"),
        tabInactiveBackground: Color(hex: "#2D2D2D"),
        tabActiveForeground: Color(hex: "#FFFFFF"),
        tabInactiveForeground: Color(hex: "#969696"),
        statusBarBackground: Color(hex: "#007ACC"),
        statusBarForeground: Color(hex: "#FFFFFF"),
        keyword: Color(hex: "#569CD6"),
        string: Color(hex: "#CE9178"),
        number: Color(hex: "#B5CEA8"),
        comment: Color(hex: "#6A9955"),
        function: Color(hex: "#DCDCAA"),
        type: Color(hex: "#4EC9B0"),
        variable: Color(hex: "#9CDCFE"),
        errorForeground: Color(hex: "#F48771"),
        warningForeground: Color(hex: "#CCA700"),
        successForeground: Color(hex: "#89D185"),
        infoForeground: Color(hex: "#75BEFF"),
        errorBackground: Color(hex: "#F48771").opacity(0.15),
        warningBackground: Color(hex: "#CCA700").opacity(0.15),
        successBackground: Color(hex: "#89D185").opacity(0.15),
        border: Color(hex: "#454545"),
        activeBorder: Color(hex: "#007ACC"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#858585"),
        diffAddedBackground: Color(hex: "#2EA043").opacity(0.4375),
        diffRemovedBackground: Color(hex: "#F85149").opacity(0.4375),
        diffHeaderBackground: Color(hex: "#264F78")
    )
    
    static let lightPlus = Theme(
        id: "light_plus",
        name: "Light+ (Default Light)",
        isDark: false,
        editorBackground: Color(hex: "#FFFFFF"),
        editorForeground: Color(hex: "#000000"),
        selection: Color(hex: "#ADD6FF"),
        cursor: Color(hex: "#000000"),
        lineNumber: Color(hex: "#237893"),
        lineNumberActive: Color(hex: "#0B216F"),
        currentLineHighlight: Color(hex: "#000000").opacity(0.07),
        bracketPair1: Color(hex: "#0431FA"),
        bracketPair2: Color(hex: "#319331"),
        bracketPair3: Color(hex: "#7B3814"),
        bracketPair4: Color(hex: "#0431FA"),
        bracketPair5: Color(hex: "#319331"),
        bracketPair6: Color(hex: "#7B3814"),
        indentGuide: Color(hex: "#D3D3D3"),
        indentGuideActive: Color(hex: "#939393"),
        sidebarBackground: Color(hex: "#F3F3F3"),
        sidebarForeground: Color(hex: "#616161"),
        sidebarSectionHeader: Color(hex: "#E7E7E7"),
        sidebarSelection: Color(hex: "#E4E6F1"),
        activityBarBackground: Color(hex: "#2C2C2C"),
        activityBarForeground: Color(hex: "#FFFFFF"),
        activityBarSelection: Color(hex: "#FFFFFF"),
        tabBarBackground: Color(hex: "#F3F3F3"),
        tabActiveBackground: Color(hex: "#FFFFFF"),
        tabInactiveBackground: Color(hex: "#ECECEC"),
        tabActiveForeground: Color(hex: "#333333"),
        tabInactiveForeground: Color(hex: "#8E8E8E"),
        statusBarBackground: Color(hex: "#007ACC"),
        statusBarForeground: Color(hex: "#FFFFFF"),
        keyword: Color(hex: "#AF00DB"),
        string: Color(hex: "#A31515"),
        number: Color(hex: "#098658"),
        comment: Color(hex: "#008000"),
        function: Color(hex: "#795E26"),
        type: Color(hex: "#267F99"),
        variable: Color(hex: "#001080"),
        errorForeground: Color(hex: "#E51400"),
        warningForeground: Color(hex: "#BF8803"),
        successForeground: Color(hex: "#388A34"),
        infoForeground: Color(hex: "#006AB1"),
        errorBackground: Color(hex: "#E51400").opacity(0.1),
        warningBackground: Color(hex: "#BF8803").opacity(0.1),
        successBackground: Color(hex: "#388A34").opacity(0.1),
        border: Color(hex: "#CCCCCC"),
        activeBorder: Color(hex: "#0066B8"),
        overlayColor: Color(hex: "#000000").opacity(0.4),
        disabledForeground: Color(hex: "#A0A0A0"),
        diffAddedBackground: Color(hex: "#2EA043").opacity(0.25),
        diffRemovedBackground: Color(hex: "#F85149").opacity(0.25),
        diffHeaderBackground: Color(hex: "#BBDAFF")
    )
    
    static let monokai = Theme(
        id: "monokai",
        name: "Monokai",
        isDark: true,
        editorBackground: Color(hex: "#272822"),
        editorForeground: Color(hex: "#F8F8F2"),
        selection: Color(hex: "#49483E"),
        cursor: Color(hex: "#F8F8F0"),
        lineNumber: Color(hex: "#90908A"),
        lineNumberActive: Color(hex: "#F8F8F2"),
        currentLineHighlight: Color(hex: "#3E3D32"),
        bracketPair1: Color(hex: "#F8F8F2"),
        bracketPair2: Color(hex: "#F92672"),
        bracketPair3: Color(hex: "#A6E22E"),
        bracketPair4: Color(hex: "#F8F8F2"),
        bracketPair5: Color(hex: "#F92672"),
        bracketPair6: Color(hex: "#A6E22E"),
        indentGuide: Color(hex: "#464741"),
        indentGuideActive: Color(hex: "#75715E"),
        sidebarBackground: Color(hex: "#272822"),
        sidebarForeground: Color(hex: "#F8F8F2"),
        sidebarSectionHeader: Color(hex: "#1E1F1C"),
        sidebarSelection: Color(hex: "#49483E"),
        activityBarBackground: Color(hex: "#1E1F1C"),
        activityBarForeground: Color(hex: "#F8F8F2"),
        activityBarSelection: Color(hex: "#F8F8F2"),
        tabBarBackground: Color(hex: "#1E1F1C"),
        tabActiveBackground: Color(hex: "#272822"),
        tabInactiveBackground: Color(hex: "#34352F"),
        tabActiveForeground: Color(hex: "#F8F8F2"),
        tabInactiveForeground: Color(hex: "#88846F"),
        statusBarBackground: Color(hex: "#75715E"),
        statusBarForeground: Color(hex: "#F8F8F2"),
        keyword: Color(hex: "#F92672"),
        string: Color(hex: "#E6DB74"),
        number: Color(hex: "#AE81FF"),
        comment: Color(hex: "#75715E"),
        function: Color(hex: "#A6E22E"),
        type: Color(hex: "#66D9EF"),
        variable: Color(hex: "#FD971F"),
        errorForeground: Color(hex: "#F92672"),
        warningForeground: Color(hex: "#E6DB74"),
        successForeground: Color(hex: "#A6E22E"),
        infoForeground: Color(hex: "#66D9EF"),
        errorBackground: Color(hex: "#F92672").opacity(0.15),
        warningBackground: Color(hex: "#E6DB74").opacity(0.15),
        successBackground: Color(hex: "#A6E22E").opacity(0.15),
        border: Color(hex: "#464741"),
        activeBorder: Color(hex: "#F92672"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#75715E"),
        diffAddedBackground: Color(hex: "#A6E22E").opacity(0.25),
        diffRemovedBackground: Color(hex: "#F92672").opacity(0.25),
        diffHeaderBackground: Color(hex: "#3E3D32")
    )
    
    static let solarizedDark = Theme(
        id: "solarized_dark",
        name: "Solarized Dark",
        isDark: true,
        editorBackground: Color(hex: "#002B36"),
        editorForeground: Color(hex: "#839496"),
        selection: Color(hex: "#274642"),
        cursor: Color(hex: "#D30102"),
        lineNumber: Color(hex: "#586E75"),
        lineNumberActive: Color(hex: "#93A1A1"),
        currentLineHighlight: Color(hex: "#0A2933"),
        bracketPair1: Color(hex: "#859900"),
        bracketPair2: Color(hex: "#2AA198"),
        bracketPair3: Color(hex: "#268BD2"),
        bracketPair4: Color(hex: "#859900"),
        bracketPair5: Color(hex: "#2AA198"),
        bracketPair6: Color(hex: "#268BD2"),
        indentGuide: Color(hex: "#073642"),
        indentGuideActive: Color(hex: "#586E75"),
        sidebarBackground: Color(hex: "#00252E"),
        sidebarForeground: Color(hex: "#93A1A1"),
        sidebarSectionHeader: Color(hex: "#001F27"),
        sidebarSelection: Color(hex: "#073642"),
        activityBarBackground: Color(hex: "#002B36"),
        activityBarForeground: Color(hex: "#93A1A1"),
        activityBarSelection: Color(hex: "#FDF6E3"),
        tabBarBackground: Color(hex: "#002B36"),
        tabActiveBackground: Color(hex: "#073642"),
        tabInactiveBackground: Color(hex: "#00212B"),
        tabActiveForeground: Color(hex: "#93A1A1"),
        tabInactiveForeground: Color(hex: "#586E75"),
        statusBarBackground: Color(hex: "#00212B"),
        statusBarForeground: Color(hex: "#93A1A1"),
        keyword: Color(hex: "#859900"),
        string: Color(hex: "#2AA198"),
        number: Color(hex: "#D33682"),
        comment: Color(hex: "#586E75"),
        function: Color(hex: "#268BD2"),
        type: Color(hex: "#CB4B16"),
        variable: Color(hex: "#B58900"),
        errorForeground: Color(hex: "#DC322F"),
        warningForeground: Color(hex: "#B58900"),
        successForeground: Color(hex: "#859900"),
        infoForeground: Color(hex: "#268BD2"),
        errorBackground: Color(hex: "#DC322F").opacity(0.15),
        warningBackground: Color(hex: "#B58900").opacity(0.15),
        successBackground: Color(hex: "#859900").opacity(0.15),
        border: Color(hex: "#2A4E56"),
        activeBorder: Color(hex: "#268BD2"),
        overlayColor: Color(hex: "#002B36").opacity(0.6),
        disabledForeground: Color(hex: "#657B83"),
        diffAddedBackground: Color(hex: "#859900").opacity(0.25),
        diffRemovedBackground: Color(hex: "#DC322F").opacity(0.25),
        diffHeaderBackground: Color(hex: "#073642")
    )
    
    static let solarizedLight = Theme(
        id: "solarized_light",
        name: "Solarized Light",
        isDark: false,
        editorBackground: Color(hex: "#FDF6E3"),
        editorForeground: Color(hex: "#657B83"),
        selection: Color(hex: "#EEE8D5"),
        cursor: Color(hex: "#D30102"),
        lineNumber: Color(hex: "#93A1A1"),
        lineNumberActive: Color(hex: "#586E75"),
        currentLineHighlight: Color(hex: "#EEE8D5"),
        bracketPair1: Color(hex: "#859900"),
        bracketPair2: Color(hex: "#2AA198"),
        bracketPair3: Color(hex: "#268BD2"),
        bracketPair4: Color(hex: "#859900"),
        bracketPair5: Color(hex: "#2AA198"),
        bracketPair6: Color(hex: "#268BD2"),
        indentGuide: Color(hex: "#EEE8D5"),
        indentGuideActive: Color(hex: "#93A1A1"),
        sidebarBackground: Color(hex: "#EEE8D5"),
        sidebarForeground: Color(hex: "#586E75"),
        sidebarSectionHeader: Color(hex: "#DDD6C1"),
        sidebarSelection: Color(hex: "#D3CBB8"),
        activityBarBackground: Color(hex: "#DDD6C1"),
        activityBarForeground: Color(hex: "#586E75"),
        activityBarSelection: Color(hex: "#073642"),
        tabBarBackground: Color(hex: "#EEE8D5"),
        tabActiveBackground: Color(hex: "#FDF6E3"),
        tabInactiveBackground: Color(hex: "#E8E0C8"),
        tabActiveForeground: Color(hex: "#073642"),
        tabInactiveForeground: Color(hex: "#93A1A1"),
        statusBarBackground: Color(hex: "#EEE8D5"),
        statusBarForeground: Color(hex: "#586E75"),
        keyword: Color(hex: "#859900"),
        string: Color(hex: "#2AA198"),
        number: Color(hex: "#D33682"),
        comment: Color(hex: "#93A1A1"),
        function: Color(hex: "#268BD2"),
        type: Color(hex: "#CB4B16"),
        variable: Color(hex: "#B58900"),
        errorForeground: Color(hex: "#DC322F"),
        warningForeground: Color(hex: "#B58900"),
        successForeground: Color(hex: "#859900"),
        infoForeground: Color(hex: "#268BD2"),
        errorBackground: Color(hex: "#DC322F").opacity(0.1),
        warningBackground: Color(hex: "#B58900").opacity(0.1),
        successBackground: Color(hex: "#859900").opacity(0.1),
        border: Color(hex: "#EEE8D5"),
        activeBorder: Color(hex: "#268BD2"),
        overlayColor: Color(hex: "#002B36").opacity(0.4),
        disabledForeground: Color(hex: "#93A1A1"),
        diffAddedBackground: Color(hex: "#859900").opacity(0.1875),
        diffRemovedBackground: Color(hex: "#DC322F").opacity(0.1875),
        diffHeaderBackground: Color(hex: "#EEE8D5")
    )
    
    static let dracula = Theme(
        id: "dracula",
        name: "Dracula",
        isDark: true,
        editorBackground: Color(hex: "#282A36"),
        editorForeground: Color(hex: "#F8F8F2"),
        selection: Color(hex: "#44475A"),
        cursor: Color(hex: "#F8F8F2"),
        lineNumber: Color(hex: "#6272A4"),
        lineNumberActive: Color(hex: "#F8F8F2"),
        currentLineHighlight: Color(hex: "#44475A"),
        bracketPair1: Color(hex: "#F8F8F2"),
        bracketPair2: Color(hex: "#FF79C6"),
        bracketPair3: Color(hex: "#8BE9FD"),
        bracketPair4: Color(hex: "#F8F8F2"),
        bracketPair5: Color(hex: "#FF79C6"),
        bracketPair6: Color(hex: "#8BE9FD"),
        indentGuide: Color(hex: "#424450"),
        indentGuideActive: Color(hex: "#6272A4"),
        sidebarBackground: Color(hex: "#21222C"),
        sidebarForeground: Color(hex: "#F8F8F2"),
        sidebarSectionHeader: Color(hex: "#191A21"),
        sidebarSelection: Color(hex: "#44475A"),
        activityBarBackground: Color(hex: "#343746"),
        activityBarForeground: Color(hex: "#F8F8F2"),
        activityBarSelection: Color(hex: "#F8F8F2"),
        tabBarBackground: Color(hex: "#191A21"),
        tabActiveBackground: Color(hex: "#282A36"),
        tabInactiveBackground: Color(hex: "#21222C"),
        tabActiveForeground: Color(hex: "#F8F8F2"),
        tabInactiveForeground: Color(hex: "#6272A4"),
        statusBarBackground: Color(hex: "#BD93F9"),
        statusBarForeground: Color(hex: "#282A36"),
        keyword: Color(hex: "#FF79C6"),
        string: Color(hex: "#F1FA8C"),
        number: Color(hex: "#BD93F9"),
        comment: Color(hex: "#6272A4"),
        function: Color(hex: "#50FA7B"),
        type: Color(hex: "#8BE9FD"),
        variable: Color(hex: "#FFB86C"),
        errorForeground: Color(hex: "#FF5555"),
        warningForeground: Color(hex: "#FFB86C"),
        successForeground: Color(hex: "#50FA7B"),
        infoForeground: Color(hex: "#8BE9FD"),
        errorBackground: Color(hex: "#FF5555").opacity(0.15),
        warningBackground: Color(hex: "#FFB86C").opacity(0.15),
        successBackground: Color(hex: "#50FA7B").opacity(0.15),
        border: Color(hex: "#44475A"),
        activeBorder: Color(hex: "#BD93F9"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#6272A4"),
        diffAddedBackground: Color(hex: "#50FA7B").opacity(0.25),
        diffRemovedBackground: Color(hex: "#FF5555").opacity(0.25),
        diffHeaderBackground: Color(hex: "#44475A")
    )
    
    static let oneDarkPro = Theme(
        id: "one_dark_pro",
        name: "One Dark Pro",
        isDark: true,
        editorBackground: Color(hex: "#282C34"),
        editorForeground: Color(hex: "#ABB2BF"),
        selection: Color(hex: "#3E4451"),
        cursor: Color(hex: "#528BFF"),
        lineNumber: Color(hex: "#4B5263"),
        lineNumberActive: Color(hex: "#ABB2BF"),
        currentLineHighlight: Color(hex: "#2C313C"),
        bracketPair1: Color(hex: "#C678DD"),
        bracketPair2: Color(hex: "#61AFEF"),
        bracketPair3: Color(hex: "#E5C07B"),
        bracketPair4: Color(hex: "#C678DD"),
        bracketPair5: Color(hex: "#61AFEF"),
        bracketPair6: Color(hex: "#E5C07B"),
        indentGuide: Color(hex: "#3B4048"),
        indentGuideActive: Color(hex: "#5C6370"),
        sidebarBackground: Color(hex: "#21252B"),
        sidebarForeground: Color(hex: "#ABB2BF"),
        sidebarSectionHeader: Color(hex: "#282C34"),
        sidebarSelection: Color(hex: "#2C313A"),
        activityBarBackground: Color(hex: "#282C34"),
        activityBarForeground: Color(hex: "#ABB2BF"),
        activityBarSelection: Color(hex: "#D7DAE0"),
        tabBarBackground: Color(hex: "#21252B"),
        tabActiveBackground: Color(hex: "#282C34"),
        tabInactiveBackground: Color(hex: "#21252B"),
        tabActiveForeground: Color(hex: "#D7DAE0"),
        tabInactiveForeground: Color(hex: "#5C6370"),
        statusBarBackground: Color(hex: "#21252B"),
        statusBarForeground: Color(hex: "#9DA5B4"),
        keyword: Color(hex: "#C678DD"),
        string: Color(hex: "#98C379"),
        number: Color(hex: "#D19A66"),
        comment: Color(hex: "#5C6370"),
        function: Color(hex: "#61AFEF"),
        type: Color(hex: "#E5C07B"),
        variable: Color(hex: "#E06C75"),
        errorForeground: Color(hex: "#E06C75"),
        warningForeground: Color(hex: "#E5C07B"),
        successForeground: Color(hex: "#98C379"),
        infoForeground: Color(hex: "#61AFEF"),
        errorBackground: Color(hex: "#E06C75").opacity(0.15),
        warningBackground: Color(hex: "#E5C07B").opacity(0.15),
        successBackground: Color(hex: "#98C379").opacity(0.15),
        border: Color(hex: "#3B4048"),
        activeBorder: Color(hex: "#528BFF"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#5C6370"),
        diffAddedBackground: Color(hex: "#98C379").opacity(0.25),
        diffRemovedBackground: Color(hex: "#E06C75").opacity(0.25),
        diffHeaderBackground: Color(hex: "#2C313C")
    )
    
    static let nord = Theme(
        id: "nord",
        name: "Nord",
        isDark: true,
        editorBackground: Color(hex: "#2E3440"),
        editorForeground: Color(hex: "#D8DEE9"),
        selection: Color(hex: "#434C5E"),
        cursor: Color(hex: "#D8DEE9"),
        lineNumber: Color(hex: "#4C566A"),
        lineNumberActive: Color(hex: "#D8DEE9"),
        currentLineHighlight: Color(hex: "#3B4252"),
        bracketPair1: Color(hex: "#EBCB8B"),
        bracketPair2: Color(hex: "#A3BE8C"),
        bracketPair3: Color(hex: "#81A1C1"),
        bracketPair4: Color(hex: "#EBCB8B"),
        bracketPair5: Color(hex: "#A3BE8C"),
        bracketPair6: Color(hex: "#81A1C1"),
        indentGuide: Color(hex: "#434C5E"),
        indentGuideActive: Color(hex: "#4C566A"),
        sidebarBackground: Color(hex: "#2E3440"),
        sidebarForeground: Color(hex: "#D8DEE9"),
        sidebarSectionHeader: Color(hex: "#3B4252"),
        sidebarSelection: Color(hex: "#3B4252"),
        activityBarBackground: Color(hex: "#2E3440"),
        activityBarForeground: Color(hex: "#D8DEE9"),
        activityBarSelection: Color(hex: "#88C0D0"),
        tabBarBackground: Color(hex: "#2E3440"),
        tabActiveBackground: Color(hex: "#3B4252"),
        tabInactiveBackground: Color(hex: "#2E3440"),
        tabActiveForeground: Color(hex: "#D8DEE9"),
        tabInactiveForeground: Color(hex: "#4C566A"),
        statusBarBackground: Color(hex: "#3B4252"),
        statusBarForeground: Color(hex: "#D8DEE9"),
        keyword: Color(hex: "#81A1C1"),
        string: Color(hex: "#A3BE8C"),
        number: Color(hex: "#B48EAD"),
        comment: Color(hex: "#616E88"),
        function: Color(hex: "#88C0D0"),
        type: Color(hex: "#8FBCBB"),
        variable: Color(hex: "#D8DEE9"),
        errorForeground: Color(hex: "#BF616A"),
        warningForeground: Color(hex: "#EBCB8B"),
        successForeground: Color(hex: "#A3BE8C"),
        infoForeground: Color(hex: "#81A1C1"),
        errorBackground: Color(hex: "#BF616A").opacity(0.15),
        warningBackground: Color(hex: "#EBCB8B").opacity(0.15),
        successBackground: Color(hex: "#A3BE8C").opacity(0.15),
        border: Color(hex: "#434C5E"),
        activeBorder: Color(hex: "#88C0D0"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#4C566A"),
        diffAddedBackground: Color(hex: "#A3BE8C").opacity(0.25),
        diffRemovedBackground: Color(hex: "#BF616A").opacity(0.25),
        diffHeaderBackground: Color(hex: "#3B4252")
    )
    
    static let githubDark = Theme(
        id: "github_dark",
        name: "GitHub Dark",
        isDark: true,
        editorBackground: Color(hex: "#0D1117"),
        editorForeground: Color(hex: "#C9D1D9"),
        selection: Color(hex: "#163356"),
        cursor: Color(hex: "#58A6FF"),
        lineNumber: Color(hex: "#484F58"),
        lineNumberActive: Color(hex: "#C9D1D9"),
        currentLineHighlight: Color(hex: "#161B22"),
        bracketPair1: Color(hex: "#79C0FF"),
        bracketPair2: Color(hex: "#D2A8FF"),
        bracketPair3: Color(hex: "#FFA657"),
        bracketPair4: Color(hex: "#79C0FF"),
        bracketPair5: Color(hex: "#D2A8FF"),
        bracketPair6: Color(hex: "#FFA657"),
        indentGuide: Color(hex: "#21262D"),
        indentGuideActive: Color(hex: "#30363D"),
        sidebarBackground: Color(hex: "#010409"),
        sidebarForeground: Color(hex: "#C9D1D9"),
        sidebarSectionHeader: Color(hex: "#161B22"),
        sidebarSelection: Color(hex: "#1F2428"),
        activityBarBackground: Color(hex: "#0D1117"),
        activityBarForeground: Color(hex: "#C9D1D9"),
        activityBarSelection: Color(hex: "#C9D1D9"),
        tabBarBackground: Color(hex: "#010409"),
        tabActiveBackground: Color(hex: "#0D1117"),
        tabInactiveBackground: Color(hex: "#010409"),
        tabActiveForeground: Color(hex: "#C9D1D9"),
        tabInactiveForeground: Color(hex: "#8B949E"),
        statusBarBackground: Color(hex: "#0D1117"),
        statusBarForeground: Color(hex: "#58A6FF"),
        keyword: Color(hex: "#FF7B72"),
        string: Color(hex: "#A5D6FF"),
        number: Color(hex: "#79C0FF"),
        comment: Color(hex: "#8B949E"),
        function: Color(hex: "#D2A8FF"),
        type: Color(hex: "#79C0FF"),
        variable: Color(hex: "#FFA657"),
        errorForeground: Color(hex: "#F85149"),
        warningForeground: Color(hex: "#D29922"),
        successForeground: Color(hex: "#3FB950"),
        infoForeground: Color(hex: "#58A6FF"),
        errorBackground: Color(hex: "#F85149").opacity(0.15),
        warningBackground: Color(hex: "#D29922").opacity(0.15),
        successBackground: Color(hex: "#3FB950").opacity(0.15),
        border: Color(hex: "#30363D"),
        activeBorder: Color(hex: "#58A6FF"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#484F58"),
        diffAddedBackground: Color(hex: "#3FB950").opacity(0.25),
        diffRemovedBackground: Color(hex: "#F85149").opacity(0.25),
        diffHeaderBackground: Color(hex: "#161B22")
    )
    
    static let githubLight = Theme(
        id: "github_light",
        name: "GitHub Light",
        isDark: false,
        editorBackground: Color(hex: "#FFFFFF"),
        editorForeground: Color(hex: "#24292F"),
        selection: Color(hex: "#B6E3FF"),
        cursor: Color(hex: "#0969DA"),
        lineNumber: Color(hex: "#8C959F"),
        lineNumberActive: Color(hex: "#24292F"),
        currentLineHighlight: Color(hex: "#F6F8FA"),
        bracketPair1: Color(hex: "#0550AE"),
        bracketPair2: Color(hex: "#8250DF"),
        bracketPair3: Color(hex: "#953800"),
        bracketPair4: Color(hex: "#0550AE"),
        bracketPair5: Color(hex: "#8250DF"),
        bracketPair6: Color(hex: "#953800"),
        indentGuide: Color(hex: "#D0D7DE"),
        indentGuideActive: Color(hex: "#8C959F"),
        sidebarBackground: Color(hex: "#F6F8FA"),
        sidebarForeground: Color(hex: "#24292F"),
        sidebarSectionHeader: Color(hex: "#EAEEF2"),
        sidebarSelection: Color(hex: "#DDFBE6"),
        activityBarBackground: Color(hex: "#F6F8FA"),
        activityBarForeground: Color(hex: "#24292F"),
        activityBarSelection: Color(hex: "#24292F"),
        tabBarBackground: Color(hex: "#F6F8FA"),
        tabActiveBackground: Color(hex: "#FFFFFF"),
        tabInactiveBackground: Color(hex: "#F6F8FA"),
        tabActiveForeground: Color(hex: "#24292F"),
        tabInactiveForeground: Color(hex: "#57606A"),
        statusBarBackground: Color(hex: "#F6F8FA"),
        statusBarForeground: Color(hex: "#0969DA"),
        keyword: Color(hex: "#CF222E"),
        string: Color(hex: "#0A3069"),
        number: Color(hex: "#0550AE"),
        comment: Color(hex: "#6E7781"),
        function: Color(hex: "#8250DF"),
        type: Color(hex: "#0550AE"),
        variable: Color(hex: "#953800"),
        errorForeground: Color(hex: "#CF222E"),
        warningForeground: Color(hex: "#9A6700"),
        successForeground: Color(hex: "#1A7F37"),
        infoForeground: Color(hex: "#0969DA"),
        errorBackground: Color(hex: "#CF222E").opacity(0.1),
        warningBackground: Color(hex: "#9A6700").opacity(0.1),
        successBackground: Color(hex: "#1A7F37").opacity(0.1),
        border: Color(hex: "#D0D7DE"),
        activeBorder: Color(hex: "#0969DA"),
        overlayColor: Color(hex: "#000000").opacity(0.4),
        disabledForeground: Color(hex: "#8C959F"),
        diffAddedBackground: Color(hex: "#1A7F37").opacity(0.1875),
        diffRemovedBackground: Color(hex: "#CF222E").opacity(0.1875),
        diffHeaderBackground: Color(hex: "#F6F8FA")
    )
    
    static let cobalt2 = Theme(
        id: "cobalt2",
        name: "Cobalt2",
        isDark: true,
        editorBackground: Color(hex: "#193549"),
        editorForeground: Color(hex: "#FFFFFF"),
        selection: Color(hex: "#0D3A58"),
        cursor: Color(hex: "#FEFB00"),
        lineNumber: Color(hex: "#3D5F7D"),
        lineNumberActive: Color(hex: "#FFFFFF"),
        currentLineHighlight: Color(hex: "#1F4662"),
        bracketPair1: Color(hex: "#FFC600"),
        bracketPair2: Color(hex: "#FF628C"),
        bracketPair3: Color(hex: "#80FFBB"),
        bracketPair4: Color(hex: "#FFC600"),
        bracketPair5: Color(hex: "#FF628C"),
        bracketPair6: Color(hex: "#80FFBB"),
        indentGuide: Color(hex: "#294B5C"),
        indentGuideActive: Color(hex: "#3D5F7D"),
        sidebarBackground: Color(hex: "#15232D"),
        sidebarForeground: Color(hex: "#FFFFFF"),
        sidebarSectionHeader: Color(hex: "#0D1A23"),
        sidebarSelection: Color(hex: "#0D3A58"),
        activityBarBackground: Color(hex: "#193549"),
        activityBarForeground: Color(hex: "#FFFFFF"),
        activityBarSelection: Color(hex: "#FFC600"),
        tabBarBackground: Color(hex: "#15232D"),
        tabActiveBackground: Color(hex: "#193549"),
        tabInactiveBackground: Color(hex: "#15232D"),
        tabActiveForeground: Color(hex: "#FFFFFF"),
        tabInactiveForeground: Color(hex: "#3D5F7D"),
        statusBarBackground: Color(hex: "#15232D"),
        statusBarForeground: Color(hex: "#FFFFFF"),
        keyword: Color(hex: "#FF9D00"),
        string: Color(hex: "#A5FF90"),
        number: Color(hex: "#FF628C"),
        comment: Color(hex: "#0088FF"),
        function: Color(hex: "#FFC600"),
        type: Color(hex: "#80FFBB"),
        variable: Color(hex: "#9EFFFF"),
        errorForeground: Color(hex: "#FF628C"),
        warningForeground: Color(hex: "#FFC600"),
        successForeground: Color(hex: "#80FFBB"),
        infoForeground: Color(hex: "#0088FF"),
        errorBackground: Color(hex: "#FF628C").opacity(0.15),
        warningBackground: Color(hex: "#FFC600").opacity(0.15),
        successBackground: Color(hex: "#80FFBB").opacity(0.15),
        border: Color(hex: "#294B5C"),
        activeBorder: Color(hex: "#0088FF"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#3D5F7D"),
        diffAddedBackground: Color(hex: "#80FFBB").opacity(0.25),
        diffRemovedBackground: Color(hex: "#FF628C").opacity(0.25),
        diffHeaderBackground: Color(hex: "#0D3A58")
    )
    
    static let ayuDark = Theme(
        id: "ayu_dark",
        name: "Ayu Dark",
        isDark: true,
        editorBackground: Color(hex: "#0A0E14"),
        editorForeground: Color(hex: "#B3B1AD"),
        selection: Color(hex: "#273747"),
        cursor: Color(hex: "#E6B450"),
        lineNumber: Color(hex: "#3D424D"),
        lineNumberActive: Color(hex: "#E6B450"),
        currentLineHighlight: Color(hex: "#0D1016"),
        bracketPair1: Color(hex: "#FFB454"),
        bracketPair2: Color(hex: "#59C2FF"),
        bracketPair3: Color(hex: "#AAD94C"),
        bracketPair4: Color(hex: "#FFB454"),
        bracketPair5: Color(hex: "#59C2FF"),
        bracketPair6: Color(hex: "#AAD94C"),
        indentGuide: Color(hex: "#1C212B"),
        indentGuideActive: Color(hex: "#3D424D"),
        sidebarBackground: Color(hex: "#0D1016"),
        sidebarForeground: Color(hex: "#B3B1AD"),
        sidebarSectionHeader: Color(hex: "#0A0E14"),
        sidebarSelection: Color(hex: "#273747"),
        activityBarBackground: Color(hex: "#0A0E14"),
        activityBarForeground: Color(hex: "#B3B1AD"),
        activityBarSelection: Color(hex: "#E6B450"),
        tabBarBackground: Color(hex: "#0D1016"),
        tabActiveBackground: Color(hex: "#0A0E14"),
        tabInactiveBackground: Color(hex: "#0D1016"),
        tabActiveForeground: Color(hex: "#B3B1AD"),
        tabInactiveForeground: Color(hex: "#3D424D"),
        statusBarBackground: Color(hex: "#0D1016"),
        statusBarForeground: Color(hex: "#B3B1AD"),
        keyword: Color(hex: "#FF8F40"),
        string: Color(hex: "#AAD94C"),
        number: Color(hex: "#DFBFFF"),
        comment: Color(hex: "#626A73"),
        function: Color(hex: "#FFB454"),
        type: Color(hex: "#59C2FF"),
        variable: Color(hex: "#B3B1AD"),
        errorForeground: Color(hex: "#FF3333"),
        warningForeground: Color(hex: "#E6B450"),
        successForeground: Color(hex: "#AAD94C"),
        infoForeground: Color(hex: "#59C2FF"),
        errorBackground: Color(hex: "#FF3333").opacity(0.15),
        warningBackground: Color(hex: "#E6B450").opacity(0.15),
        successBackground: Color(hex: "#AAD94C").opacity(0.15),
        border: Color(hex: "#1C212B"),
        activeBorder: Color(hex: "#59C2FF"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#3D424D"),
        diffAddedBackground: Color(hex: "#AAD94C").opacity(0.25),
        diffRemovedBackground: Color(hex: "#FF3333").opacity(0.25),
        diffHeaderBackground: Color(hex: "#0D1016")
    )
    
    static let ayuLight = Theme(
        id: "ayu_light",
        name: "Ayu Light",
        isDark: false,
        editorBackground: Color(hex: "#FAFAFA"),
        editorForeground: Color(hex: "#5C6166"),
        selection: Color(hex: "#D1E4F4"),
        cursor: Color(hex: "#FF9940"),
        lineNumber: Color(hex: "#9DA2A6"),
        lineNumberActive: Color(hex: "#FF9940"),
        currentLineHighlight: Color(hex: "#EFF0F1"),
        bracketPair1: Color(hex: "#F2AE49"),
        bracketPair2: Color(hex: "#399EE6"),
        bracketPair3: Color(hex: "#86B300"),
        bracketPair4: Color(hex: "#F2AE49"),
        bracketPair5: Color(hex: "#399EE6"),
        bracketPair6: Color(hex: "#86B300"),
        indentGuide: Color(hex: "#E7E8E9"),
        indentGuideActive: Color(hex: "#9DA2A6"),
        sidebarBackground: Color(hex: "#F0F0F0"),
        sidebarForeground: Color(hex: "#5C6166"),
        sidebarSectionHeader: Color(hex: "#E7E7E7"),
        sidebarSelection: Color(hex: "#D1E4F4"),
        activityBarBackground: Color(hex: "#F0F0F0"),
        activityBarForeground: Color(hex: "#5C6166"),
        activityBarSelection: Color(hex: "#FF9940"),
        tabBarBackground: Color(hex: "#F0F0F0"),
        tabActiveBackground: Color(hex: "#FAFAFA"),
        tabInactiveBackground: Color(hex: "#F0F0F0"),
        tabActiveForeground: Color(hex: "#5C6166"),
        tabInactiveForeground: Color(hex: "#9DA2A6"),
        statusBarBackground: Color(hex: "#F0F0F0"),
        statusBarForeground: Color(hex: "#5C6166"),
        keyword: Color(hex: "#FA8D3E"),
        string: Color(hex: "#86B300"),
        number: Color(hex: "#A37ACC"),
        comment: Color(hex: "#ABB0B6"),
        function: Color(hex: "#F2AE49"),
        type: Color(hex: "#399EE6"),
        variable: Color(hex: "#5C6166"),
        errorForeground: Color(hex: "#F07178"),
        warningForeground: Color(hex: "#F2AE49"),
        successForeground: Color(hex: "#86B300"),
        infoForeground: Color(hex: "#399EE6"),
        errorBackground: Color(hex: "#F07178").opacity(0.1),
        warningBackground: Color(hex: "#F2AE49").opacity(0.1),
        successBackground: Color(hex: "#86B300").opacity(0.1),
        border: Color(hex: "#E7E8E9"),
        activeBorder: Color(hex: "#399EE6"),
        overlayColor: Color(hex: "#000000").opacity(0.4),
        disabledForeground: Color(hex: "#9DA2A6"),
        diffAddedBackground: Color(hex: "#86B300").opacity(0.1875),
        diffRemovedBackground: Color(hex: "#F07178").opacity(0.1875),
        diffHeaderBackground: Color(hex: "#EFF0F1")
    )
    
    static let ayuMirage = Theme(
        id: "ayu_mirage",
        name: "Ayu Mirage",
        isDark: true,
        editorBackground: Color(hex: "#1F2430"),
        editorForeground: Color(hex: "#CBCCC6"),
        selection: Color(hex: "#33415E"),
        cursor: Color(hex: "#FFCC66"),
        lineNumber: Color(hex: "#707A8C"),
        lineNumberActive: Color(hex: "#FFCC66"),
        currentLineHighlight: Color(hex: "#232834"),
        bracketPair1: Color(hex: "#FFD580"),
        bracketPair2: Color(hex: "#73D0FF"),
        bracketPair3: Color(hex: "#BAE67E"),
        bracketPair4: Color(hex: "#FFD580"),
        bracketPair5: Color(hex: "#73D0FF"),
        bracketPair6: Color(hex: "#BAE67E"),
        indentGuide: Color(hex: "#2D3640"),
        indentGuideActive: Color(hex: "#707A8C"),
        sidebarBackground: Color(hex: "#232834"),
        sidebarForeground: Color(hex: "#CBCCC6"),
        sidebarSectionHeader: Color(hex: "#1F2430"),
        sidebarSelection: Color(hex: "#33415E"),
        activityBarBackground: Color(hex: "#1F2430"),
        activityBarForeground: Color(hex: "#CBCCC6"),
        activityBarSelection: Color(hex: "#FFCC66"),
        tabBarBackground: Color(hex: "#232834"),
        tabActiveBackground: Color(hex: "#1F2430"),
        tabInactiveBackground: Color(hex: "#232834"),
        tabActiveForeground: Color(hex: "#CBCCC6"),
        tabInactiveForeground: Color(hex: "#707A8C"),
        statusBarBackground: Color(hex: "#232834"),
        statusBarForeground: Color(hex: "#CBCCC6"),
        keyword: Color(hex: "#FFA759"),
        string: Color(hex: "#BAE67E"),
        number: Color(hex: "#D4BFFF"),
        comment: Color(hex: "#5C6773"),
        function: Color(hex: "#FFD580"),
        type: Color(hex: "#73D0FF"),
        variable: Color(hex: "#CBCCC6"),
        errorForeground: Color(hex: "#F28779"),
        warningForeground: Color(hex: "#FFD580"),
        successForeground: Color(hex: "#BAE67E"),
        infoForeground: Color(hex: "#73D0FF"),
        errorBackground: Color(hex: "#F28779").opacity(0.15),
        warningBackground: Color(hex: "#FFD580").opacity(0.15),
        successBackground: Color(hex: "#BAE67E").opacity(0.15),
        border: Color(hex: "#2D3640"),
        activeBorder: Color(hex: "#73D0FF"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#707A8C"),
        diffAddedBackground: Color(hex: "#BAE67E").opacity(0.25),
        diffRemovedBackground: Color(hex: "#F28779").opacity(0.25),
        diffHeaderBackground: Color(hex: "#232834")
    )
    
    static let quietLight = Theme(
        id: "quiet_light",
        name: "Quiet Light",
        isDark: false,
        editorBackground: Color(hex: "#F5F5F5"),
        editorForeground: Color(hex: "#333333"),
        selection: Color(hex: "#C9D0D9"),
        cursor: Color(hex: "#54494B"),
        lineNumber: Color(hex: "#AAAAAA"),
        lineNumberActive: Color(hex: "#333333"),
        currentLineHighlight: Color(hex: "#E4F6D4"),
        bracketPair1: Color(hex: "#7A3E9D"),
        bracketPair2: Color(hex: "#448C27"),
        bracketPair3: Color(hex: "#4B83CD"),
        bracketPair4: Color(hex: "#7A3E9D"),
        bracketPair5: Color(hex: "#448C27"),
        bracketPair6: Color(hex: "#4B83CD"),
        indentGuide: Color(hex: "#E0E0E0"),
        indentGuideActive: Color(hex: "#AAAAAA"),
        sidebarBackground: Color(hex: "#E7E7E7"),
        sidebarForeground: Color(hex: "#333333"),
        sidebarSectionHeader: Color(hex: "#DDDDDD"),
        sidebarSelection: Color(hex: "#C9D0D9"),
        activityBarBackground: Color(hex: "#E7E7E7"),
        activityBarForeground: Color(hex: "#333333"),
        activityBarSelection: Color(hex: "#333333"),
        tabBarBackground: Color(hex: "#E7E7E7"),
        tabActiveBackground: Color(hex: "#F5F5F5"),
        tabInactiveBackground: Color(hex: "#E7E7E7"),
        tabActiveForeground: Color(hex: "#333333"),
        tabInactiveForeground: Color(hex: "#AAAAAA"),
        statusBarBackground: Color(hex: "#E7E7E7"),
        statusBarForeground: Color(hex: "#333333"),
        keyword: Color(hex: "#4B83CD"),
        string: Color(hex: "#448C27"),
        number: Color(hex: "#AB6526"),
        comment: Color(hex: "#AAAAAA"),
        function: Color(hex: "#7A3E9D"),
        type: Color(hex: "#7A3E9D"),
        variable: Color(hex: "#333333"),
        errorForeground: Color(hex: "#D73A49"),
        warningForeground: Color(hex: "#CB6200"),
        successForeground: Color(hex: "#22863A"),
        infoForeground: Color(hex: "#4B83CD"),
        errorBackground: Color(hex: "#D73A49").opacity(0.1),
        warningBackground: Color(hex: "#CB6200").opacity(0.1),
        successBackground: Color(hex: "#22863A").opacity(0.1),
        border: Color(hex: "#E0E0E0"),
        activeBorder: Color(hex: "#4B83CD"),
        overlayColor: Color(hex: "#000000").opacity(0.4),
        disabledForeground: Color(hex: "#AAAAAA"),
        diffAddedBackground: Color(hex: "#22863A").opacity(0.1875),
        diffRemovedBackground: Color(hex: "#D73A49").opacity(0.1875),
        diffHeaderBackground: Color(hex: "#E4F6D4")
    )
    
    static let red = Theme(
        id: "red",
        name: "Red",
        isDark: true,
        editorBackground: Color(hex: "#390000"),
        editorForeground: Color(hex: "#F8F8F8"),
        selection: Color(hex: "#750000"),
        cursor: Color(hex: "#FF0000"),
        lineNumber: Color(hex: "#FF6666"),
        lineNumberActive: Color(hex: "#FFFFFF"),
        currentLineHighlight: Color(hex: "#500000"),
        bracketPair1: Color(hex: "#FFFF66"),
        bracketPair2: Color(hex: "#AAFFAA"),
        bracketPair3: Color(hex: "#AADDFF"),
        bracketPair4: Color(hex: "#FFFF66"),
        bracketPair5: Color(hex: "#AAFFAA"),
        bracketPair6: Color(hex: "#AADDFF"),
        indentGuide: Color(hex: "#550000"),
        indentGuideActive: Color(hex: "#CC6666"),
        sidebarBackground: Color(hex: "#300000"),
        sidebarForeground: Color(hex: "#F8F8F8"),
        sidebarSectionHeader: Color(hex: "#500000"),
        sidebarSelection: Color(hex: "#750000"),
        activityBarBackground: Color(hex: "#390000"),
        activityBarForeground: Color(hex: "#F8F8F8"),
        activityBarSelection: Color(hex: "#FF0000"),
        tabBarBackground: Color(hex: "#300000"),
        tabActiveBackground: Color(hex: "#390000"),
        tabInactiveBackground: Color(hex: "#300000"),
        tabActiveForeground: Color(hex: "#FFFFFF"),
        tabInactiveForeground: Color(hex: "#CC6666"),
        statusBarBackground: Color(hex: "#FF0000"),
        statusBarForeground: Color(hex: "#FFFFFF"),
        keyword: Color(hex: "#FF6666"),
        string: Color(hex: "#FFA0A0"),
        number: Color(hex: "#FFD0D0"),
        comment: Color(hex: "#CC6666"),
        function: Color(hex: "#FFFF66"),
        type: Color(hex: "#AAFFAA"),
        variable: Color(hex: "#AADDFF"),
        errorForeground: Color(hex: "#FF0000"),
        warningForeground: Color(hex: "#FFFF66"),
        successForeground: Color(hex: "#AAFFAA"),
        infoForeground: Color(hex: "#AADDFF"),
        errorBackground: Color(hex: "#FF0000").opacity(0.15),
        warningBackground: Color(hex: "#FFFF66").opacity(0.15),
        successBackground: Color(hex: "#AAFFAA").opacity(0.15),
        border: Color(hex: "#550000"),
        activeBorder: Color(hex: "#FF0000"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#CC6666"),
        diffAddedBackground: Color(hex: "#AAFFAA").opacity(0.25),
        diffRemovedBackground: Color(hex: "#FF0000").opacity(0.25),
        diffHeaderBackground: Color(hex: "#500000")
    )
    
    static let tomorrowNight = Theme(
        id: "tomorrow_night",
        name: "Tomorrow Night",
        isDark: true,
        editorBackground: Color(hex: "#1D1F21"),
        editorForeground: Color(hex: "#C5C8C6"),
        selection: Color(hex: "#373B41"),
        cursor: Color(hex: "#AEAFAD"),
        lineNumber: Color(hex: "#969896"),
        lineNumberActive: Color(hex: "#C5C8C6"),
        currentLineHighlight: Color(hex: "#282A2E"),
        bracketPair1: Color(hex: "#F0C674"),
        bracketPair2: Color(hex: "#B5BD68"),
        bracketPair3: Color(hex: "#81A2BE"),
        bracketPair4: Color(hex: "#F0C674"),
        bracketPair5: Color(hex: "#B5BD68"),
        bracketPair6: Color(hex: "#81A2BE"),
        indentGuide: Color(hex: "#373B41"),
        indentGuideActive: Color(hex: "#969896"),
        sidebarBackground: Color(hex: "#1D1F21"),
        sidebarForeground: Color(hex: "#C5C8C6"),
        sidebarSectionHeader: Color(hex: "#282A2E"),
        sidebarSelection: Color(hex: "#373B41"),
        activityBarBackground: Color(hex: "#1D1F21"),
        activityBarForeground: Color(hex: "#C5C8C6"),
        activityBarSelection: Color(hex: "#81A2BE"),
        tabBarBackground: Color(hex: "#1D1F21"),
        tabActiveBackground: Color(hex: "#282A2E"),
        tabInactiveBackground: Color(hex: "#1D1F21"),
        tabActiveForeground: Color(hex: "#C5C8C6"),
        tabInactiveForeground: Color(hex: "#969896"),
        statusBarBackground: Color(hex: "#282A2E"),
        statusBarForeground: Color(hex: "#C5C8C6"),
        keyword: Color(hex: "#B294BB"),
        string: Color(hex: "#B5BD68"),
        number: Color(hex: "#DE935F"),
        comment: Color(hex: "#969896"),
        function: Color(hex: "#81A2BE"),
        type: Color(hex: "#F0C674"),
        variable: Color(hex: "#CC6666"),
        errorForeground: Color(hex: "#CC6666"),
        warningForeground: Color(hex: "#F0C674"),
        successForeground: Color(hex: "#B5BD68"),
        infoForeground: Color(hex: "#81A2BE"),
        errorBackground: Color(hex: "#CC6666").opacity(0.15),
        warningBackground: Color(hex: "#F0C674").opacity(0.15),
        successBackground: Color(hex: "#B5BD68").opacity(0.15),
        border: Color(hex: "#373B41"),
        activeBorder: Color(hex: "#81A2BE"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#969896"),
        diffAddedBackground: Color(hex: "#B5BD68").opacity(0.25),
        diffRemovedBackground: Color(hex: "#CC6666").opacity(0.25),
        diffHeaderBackground: Color(hex: "#282A2E")
    )
    
    static let tomorrowNightBlue = Theme(
        id: "tomorrow_night_blue",
        name: "Tomorrow Night Blue",
        isDark: true,
        editorBackground: Color(hex: "#002451"),
        editorForeground: Color(hex: "#FFFFFF"),
        selection: Color(hex: "#003F8E"),
        cursor: Color(hex: "#FFFFFF"),
        lineNumber: Color(hex: "#7285B7"),
        lineNumberActive: Color(hex: "#FFFFFF"),
        currentLineHighlight: Color(hex: "#00346E"),
        bracketPair1: Color(hex: "#FFEEAD"),
        bracketPair2: Color(hex: "#D1F1A9"),
        bracketPair3: Color(hex: "#BBDAFF"),
        bracketPair4: Color(hex: "#FFEEAD"),
        bracketPair5: Color(hex: "#D1F1A9"),
        bracketPair6: Color(hex: "#BBDAFF"),
        indentGuide: Color(hex: "#003875"),
        indentGuideActive: Color(hex: "#7285B7"),
        sidebarBackground: Color(hex: "#001E40"),
        sidebarForeground: Color(hex: "#FFFFFF"),
        sidebarSectionHeader: Color(hex: "#003875"),
        sidebarSelection: Color(hex: "#003F8E"),
        activityBarBackground: Color(hex: "#002451"),
        activityBarForeground: Color(hex: "#FFFFFF"),
        activityBarSelection: Color(hex: "#BBDAFF"),
        tabBarBackground: Color(hex: "#001E40"),
        tabActiveBackground: Color(hex: "#002451"),
        tabInactiveBackground: Color(hex: "#001E40"),
        tabActiveForeground: Color(hex: "#FFFFFF"),
        tabInactiveForeground: Color(hex: "#7285B7"),
        statusBarBackground: Color(hex: "#003875"),
        statusBarForeground: Color(hex: "#FFFFFF"),
        keyword: Color(hex: "#EBBBFF"),
        string: Color(hex: "#D1F1A9"),
        number: Color(hex: "#FFC58F"),
        comment: Color(hex: "#7285B7"),
        function: Color(hex: "#BBDAFF"),
        type: Color(hex: "#FFEEAD"),
        variable: Color(hex: "#FF9DA4"),
        errorForeground: Color(hex: "#FF9DA4"),
        warningForeground: Color(hex: "#FFEEAD"),
        successForeground: Color(hex: "#D1F1A9"),
        infoForeground: Color(hex: "#BBDAFF"),
        errorBackground: Color(hex: "#FF9DA4").opacity(0.15),
        warningBackground: Color(hex: "#FFEEAD").opacity(0.15),
        successBackground: Color(hex: "#D1F1A9").opacity(0.15),
        border: Color(hex: "#003875"),
        activeBorder: Color(hex: "#BBDAFF"),
        overlayColor: Color(hex: "#000000").opacity(0.6),
        disabledForeground: Color(hex: "#7285B7"),
        diffAddedBackground: Color(hex: "#D1F1A9").opacity(0.25),
        diffRemovedBackground: Color(hex: "#FF9DA4").opacity(0.25),
        diffHeaderBackground: Color(hex: "#00346E")
    )
    
    static let highContrast = Theme(
        id: "high_contrast",
        name: "High Contrast",
        isDark: true,
        editorBackground: Color(hex: "#000000"),
        editorForeground: Color(hex: "#FFFFFF"),
        selection: Color(hex: "#FFFFFF").opacity(0.3),
        cursor: Color(hex: "#FFFFFF"),
        lineNumber: Color(hex: "#FFFFFF"),
        lineNumberActive: Color(hex: "#FFFFFF"),
        currentLineHighlight: Color(hex: "#FFFFFF").opacity(0.1),
        bracketPair1: Color(hex: "#FFD700"),
        bracketPair2: Color(hex: "#00FF00"),
        bracketPair3: Color(hex: "#00BFFF"),
        bracketPair4: Color(hex: "#FFD700"),
        bracketPair5: Color(hex: "#00FF00"),
        bracketPair6: Color(hex: "#00BFFF"),
        indentGuide: Color(hex: "#FFFFFF").opacity(0.2),
        indentGuideActive: Color(hex: "#FFFFFF").opacity(0.5),
        sidebarBackground: Color(hex: "#000000"),
        sidebarForeground: Color(hex: "#FFFFFF"),
        sidebarSectionHeader: Color(hex: "#000000"),
        sidebarSelection: Color(hex: "#FFFFFF").opacity(0.15),
        activityBarBackground: Color(hex: "#000000"),
        activityBarForeground: Color(hex: "#FFFFFF"),
        activityBarSelection: Color(hex: "#FFFFFF"),
        tabBarBackground: Color(hex: "#000000"),
        tabActiveBackground: Color(hex: "#000000"),
        tabInactiveBackground: Color(hex: "#000000"),
        tabActiveForeground: Color(hex: "#FFFFFF"),
        tabInactiveForeground: Color(hex: "#FFFFFF").opacity(0.6),
        statusBarBackground: Color(hex: "#0000AA"),
        statusBarForeground: Color(hex: "#FFFFFF"),
        keyword: Color(hex: "#569CD6"),
        string: Color(hex: "#CE9178"),
        number: Color(hex: "#B5CEA8"),
        comment: Color(hex: "#7CA668"),
        function: Color(hex: "#DCDCAA"),
        type: Color(hex: "#4EC9B0"),
        variable: Color(hex: "#9CDCFE"),
        errorForeground: Color(hex: "#FF0000"),
        warningForeground: Color(hex: "#FFD700"),
        successForeground: Color(hex: "#00FF00"),
        infoForeground: Color(hex: "#00BFFF"),
        errorBackground: Color(hex: "#FF0000").opacity(0.2),
        warningBackground: Color(hex: "#FFD700").opacity(0.2),
        successBackground: Color(hex: "#00FF00").opacity(0.2),
        border: Color(hex: "#6FC3DF"),
        activeBorder: Color(hex: "#FFFFFF"),
        overlayColor: Color(hex: "#000000").opacity(0.6),
        disabledForeground: Color(hex: "#FFFFFF").opacity(0.5),
        diffAddedBackground: Color(hex: "#00FF00").opacity(0.3),
        diffRemovedBackground: Color(hex: "#FF0000").opacity(0.3),
        diffHeaderBackground: Color(hex: "#0000AA")
    )
    

    static let aurora = Theme(
        id: "aurora",
        name: "Aurora",
        isDark: true,
        editorBackground: Color(hex: "#2E3440"),
        editorForeground: Color(hex: "#ECEFF4"),
        selection: Color(hex: "#434C5E"),
        cursor: Color(hex: "#ECEFF4"),
        lineNumber: Color(hex: "#4C566A"),
        lineNumberActive: Color(hex: "#ECEFF4"),
        currentLineHighlight: Color(hex: "#3B4252"),
        bracketPair1: Color(hex: "#88C0D0"),
        bracketPair2: Color(hex: "#B48EAD"),
        bracketPair3: Color(hex: "#A3BE8C"),
        bracketPair4: Color(hex: "#88C0D0"),
        bracketPair5: Color(hex: "#B48EAD"),
        bracketPair6: Color(hex: "#A3BE8C"),
        indentGuide: Color(hex: "#434C5E"),
        indentGuideActive: Color(hex: "#4C566A"),
        sidebarBackground: Color(hex: "#2E3440"),
        sidebarForeground: Color(hex: "#ECEFF4"),
        sidebarSectionHeader: Color(hex: "#3B4252"),
        sidebarSelection: Color(hex: "#3B4252"),
        activityBarBackground: Color(hex: "#2E3440"),
        activityBarForeground: Color(hex: "#ECEFF4"),
        activityBarSelection: Color(hex: "#88C0D0"),
        tabBarBackground: Color(hex: "#2E3440"),
        tabActiveBackground: Color(hex: "#3B4252"),
        tabInactiveBackground: Color(hex: "#2E3440"),
        tabActiveForeground: Color(hex: "#ECEFF4"),
        tabInactiveForeground: Color(hex: "#4C566A"),
        statusBarBackground: Color(hex: "#3B4252"),
        statusBarForeground: Color(hex: "#ECEFF4"),
        keyword: Color(hex: "#81A1C1"),
        string: Color(hex: "#A3BE8C"),
        number: Color(hex: "#B48EAD"),
        comment: Color(hex: "#616E88"),
        function: Color(hex: "#88C0D0"),
        type: Color(hex: "#8FBCBB"),
        variable: Color(hex: "#D08770"),
        errorForeground: Color(hex: "#BF616A"),
        warningForeground: Color(hex: "#EBCB8B"),
        successForeground: Color(hex: "#A3BE8C"),
        infoForeground: Color(hex: "#81A1C1"),
        errorBackground: Color(hex: "#BF616A").opacity(0.15),
        warningBackground: Color(hex: "#EBCB8B").opacity(0.15),
        successBackground: Color(hex: "#A3BE8C").opacity(0.15),
        border: Color(hex: "#434C5E"),
        activeBorder: Color(hex: "#88C0D0"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#4C566A"),
        diffAddedBackground: Color(hex: "#A3BE8C").opacity(0.25),
        diffRemovedBackground: Color(hex: "#BF616A").opacity(0.25),
        diffHeaderBackground: Color(hex: "#3B4252")
    )

    static let tokyoNight = Theme(
        id: "tokyo_night",
        name: "Tokyo Night",
        isDark: true,
        editorBackground: Color(hex: "#1A1B26"),
        editorForeground: Color(hex: "#A9B1D6"),
        selection: Color(hex: "#283457"),
        cursor: Color(hex: "#C0CAF5"),
        lineNumber: Color(hex: "#3B4261"),
        lineNumberActive: Color(hex: "#A9B1D6"),
        currentLineHighlight: Color(hex: "#1E2030"),
        bracketPair1: Color(hex: "#7AA2F7"),
        bracketPair2: Color(hex: "#BB9AF7"),
        bracketPair3: Color(hex: "#9ECE6A"),
        bracketPair4: Color(hex: "#7AA2F7"),
        bracketPair5: Color(hex: "#BB9AF7"),
        bracketPair6: Color(hex: "#9ECE6A"),
        indentGuide: Color(hex: "#292E42"),
        indentGuideActive: Color(hex: "#3B4261"),
        sidebarBackground: Color(hex: "#16161E"),
        sidebarForeground: Color(hex: "#A9B1D6"),
        sidebarSectionHeader: Color(hex: "#1A1B26"),
        sidebarSelection: Color(hex: "#283457"),
        activityBarBackground: Color(hex: "#1A1B26"),
        activityBarForeground: Color(hex: "#A9B1D6"),
        activityBarSelection: Color(hex: "#7AA2F7"),
        tabBarBackground: Color(hex: "#16161E"),
        tabActiveBackground: Color(hex: "#1A1B26"),
        tabInactiveBackground: Color(hex: "#16161E"),
        tabActiveForeground: Color(hex: "#A9B1D6"),
        tabInactiveForeground: Color(hex: "#565F89"),
        statusBarBackground: Color(hex: "#16161E"),
        statusBarForeground: Color(hex: "#A9B1D6"),
        keyword: Color(hex: "#BB9AF7"),
        string: Color(hex: "#9ECE6A"),
        number: Color(hex: "#FF9E64"),
        comment: Color(hex: "#565F89"),
        function: Color(hex: "#7AA2F7"),
        type: Color(hex: "#7DCFFF"),
        variable: Color(hex: "#C0CAF5"),
        errorForeground: Color(hex: "#F7768E"),
        warningForeground: Color(hex: "#E0AF68"),
        successForeground: Color(hex: "#9ECE6A"),
        infoForeground: Color(hex: "#7AA2F7"),
        errorBackground: Color(hex: "#F7768E").opacity(0.15),
        warningBackground: Color(hex: "#E0AF68").opacity(0.15),
        successBackground: Color(hex: "#9ECE6A").opacity(0.15),
        border: Color(hex: "#292E42"),
        activeBorder: Color(hex: "#7AA2F7"),
        overlayColor: Color(hex: "#000000").opacity(0.5),
        disabledForeground: Color(hex: "#565F89"),
        diffAddedBackground: Color(hex: "#9ECE6A").opacity(0.25),
        diffRemovedBackground: Color(hex: "#F7768E").opacity(0.25),
        diffHeaderBackground: Color(hex: "#1E2030")
    )

    // MARK: - All Themes
    static let allThemes: [Theme] = [
        .darkPlus,
        .lightPlus,
        .monokai,
        .solarizedDark,
        .solarizedLight,
        .dracula,
        .oneDarkPro,
        .nord,
        .githubDark,
        .githubLight,
        .cobalt2,
        .ayuDark,
        .ayuLight,
        .ayuMirage,
        .quietLight,
        .red,
        .tomorrowNight,
        .tomorrowNightBlue,
        .highContrast,
        .aurora,
        .tokyoNight
    ]
}