import SwiftUI

struct Theme: Identifiable, Equatable, Hashable {
    let id: String
    let name: String
    let isDark: Bool
    
    // Editor Colors
    let editorBackground: Color
    let editorForeground: Color
    let selection: Color
    let cursor: Color
    let lineNumber: Color
    let lineNumberActive: Color
    let currentLineHighlight: Color
    let bracketPair1: Color
    let bracketPair2: Color
    let bracketPair3: Color
    let bracketPair4: Color
    let bracketPair5: Color
    let bracketPair6: Color
    let indentGuide: Color
    let indentGuideActive: Color
    
    // UI Colors
    let sidebarBackground: Color
    let sidebarForeground: Color
    let sidebarSectionHeader: Color
    let sidebarSelection: Color
    let activityBarBackground: Color
    let activityBarForeground: Color
    let activityBarSelection: Color
    let tabBarBackground: Color
    let tabActiveBackground: Color
    let tabInactiveBackground: Color
    let tabActiveForeground: Color
    let tabInactiveForeground: Color
    let statusBarBackground: Color
    let statusBarForeground: Color
    
    // Syntax Colors
    let keyword: Color
    let string: Color
    let number: Color
    let comment: Color
    let function: Color
    let type: Color
    let variable: Color
    
    // Helper for Hex Colors
    static func hex(_ hex: String) -> Color {
        var hexSanitized = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        hexSanitized = hexSanitized.replacingOccurrences(of: "#", with: "")
        
        var rgb: UInt64 = 0
        Scanner(string: hexSanitized).scanHexInt64(&rgb)
        
        let r = Double((rgb & 0xFF0000) >> 16) / 255.0
        let g = Double((rgb & 0x00FF00) >> 8) / 255.0
        let b = Double(rgb & 0x0000FF) / 255.0
        
        return Color(red: r, green: g, blue: b)
    }
    
    // MARK: - VS Code Default Themes
    
    static let darkPlus = Theme(
        id: "dark_plus",
        name: "Dark+ (Default Dark)",
        isDark: true,
        editorBackground: hex("#1E1E1E"),
        editorForeground: hex("#D4D4D4"),
        selection: hex("#264F78"),
        cursor: hex("#AEAFAD"),
        lineNumber: hex("#858585"),
        lineNumberActive: hex("#C6C6C6"),
        currentLineHighlight: hex("#FFFFFF").opacity(0.1),
        bracketPair1: hex("#FFD700"),
        bracketPair2: hex("#DA70D6"),
        bracketPair3: hex("#179FFF"),
        bracketPair4: hex("#FFD700"),
        bracketPair5: hex("#DA70D6"),
        bracketPair6: hex("#179FFF"),
        indentGuide: hex("#404040"),
        indentGuideActive: hex("#707070"),
        sidebarBackground: hex("#252526"),
        sidebarForeground: hex("#CCCCCC"),
        sidebarSectionHeader: hex("#383838"),
        sidebarSelection: hex("#37373D"),
        activityBarBackground: hex("#333333"),
        activityBarForeground: hex("#FFFFFF"),
        activityBarSelection: hex("#FFFFFF"),
        tabBarBackground: hex("#252526"),
        tabActiveBackground: hex("#1E1E1E"),
        tabInactiveBackground: hex("#2D2D2D"),
        tabActiveForeground: hex("#FFFFFF"),
        tabInactiveForeground: hex("#969696"),
        statusBarBackground: hex("#007ACC"),
        statusBarForeground: hex("#FFFFFF"),
        keyword: hex("#C586C0"),
        string: hex("#CE9178"),
        number: hex("#B5CEA8"),
        comment: hex("#6A9955"),
        function: hex("#DCDCAA"),
        type: hex("#4EC9B0"),
        variable: hex("#9CDCFE")
    )
    
    static let lightPlus = Theme(
        id: "light_plus",
        name: "Light+ (Default Light)",
        isDark: false,
        editorBackground: hex("#FFFFFF"),
        editorForeground: hex("#000000"),
        selection: hex("#ADD6FF"),
        cursor: hex("#000000"),
        lineNumber: hex("#237893"),
        lineNumberActive: hex("#0B216F"),
        currentLineHighlight: hex("#000000").opacity(0.07),
        bracketPair1: hex("#0431FA"),
        bracketPair2: hex("#319331"),
        bracketPair3: hex("#7B3814"),
        bracketPair4: hex("#0431FA"),
        bracketPair5: hex("#319331"),
        bracketPair6: hex("#7B3814"),
        indentGuide: hex("#D3D3D3"),
        indentGuideActive: hex("#939393"),
        sidebarBackground: hex("#F3F3F3"),
        sidebarForeground: hex("#616161"),
        sidebarSectionHeader: hex("#E7E7E7"),
        sidebarSelection: hex("#E4E6F1"),
        activityBarBackground: hex("#2C2C2C"),
        activityBarForeground: hex("#FFFFFF"),
        activityBarSelection: hex("#FFFFFF"),
        tabBarBackground: hex("#F3F3F3"),
        tabActiveBackground: hex("#FFFFFF"),
        tabInactiveBackground: hex("#ECECEC"),
        tabActiveForeground: hex("#333333"),
        tabInactiveForeground: hex("#8E8E8E"),
        statusBarBackground: hex("#007ACC"),
        statusBarForeground: hex("#FFFFFF"),
        keyword: hex("#AF00DB"),
        string: hex("#A31515"),
        number: hex("#098658"),
        comment: hex("#008000"),
        function: hex("#795E26"),
        type: hex("#267F99"),
        variable: hex("#001080")
    )
    
    static let monokai = Theme(
        id: "monokai",
        name: "Monokai",
        isDark: true,
        editorBackground: hex("#272822"),
        editorForeground: hex("#F8F8F2"),
        selection: hex("#49483E"),
        cursor: hex("#F8F8F0"),
        lineNumber: hex("#90908A"),
        lineNumberActive: hex("#F8F8F2"),
        currentLineHighlight: hex("#3E3D32"),
        bracketPair1: hex("#F8F8F2"),
        bracketPair2: hex("#F92672"),
        bracketPair3: hex("#A6E22E"),
        bracketPair4: hex("#F8F8F2"),
        bracketPair5: hex("#F92672"),
        bracketPair6: hex("#A6E22E"),
        indentGuide: hex("#464741"),
        indentGuideActive: hex("#75715E"),
        sidebarBackground: hex("#272822"),
        sidebarForeground: hex("#F8F8F2"),
        sidebarSectionHeader: hex("#1E1F1C"),
        sidebarSelection: hex("#49483E"),
        activityBarBackground: hex("#1E1F1C"),
        activityBarForeground: hex("#F8F8F2"),
        activityBarSelection: hex("#F8F8F2"),
        tabBarBackground: hex("#1E1F1C"),
        tabActiveBackground: hex("#272822"),
        tabInactiveBackground: hex("#34352F"),
        tabActiveForeground: hex("#F8F8F2"),
        tabInactiveForeground: hex("#88846F"),
        statusBarBackground: hex("#75715E"),
        statusBarForeground: hex("#F8F8F2"),
        keyword: hex("#F92672"),
        string: hex("#E6DB74"),
        number: hex("#AE81FF"),
        comment: hex("#75715E"),
        function: hex("#A6E22E"),
        type: hex("#66D9EF"),
        variable: hex("#FD971F")
    )
    
    static let solarizedDark = Theme(
        id: "solarized_dark",
        name: "Solarized Dark",
        isDark: true,
        editorBackground: hex("#002B36"),
        editorForeground: hex("#839496"),
        selection: hex("#274642"),
        cursor: hex("#D30102"),
        lineNumber: hex("#586E75"),
        lineNumberActive: hex("#93A1A1"),
        currentLineHighlight: hex("#0A2933"),
        bracketPair1: hex("#859900"),
        bracketPair2: hex("#2AA198"),
        bracketPair3: hex("#268BD2"),
        bracketPair4: hex("#859900"),
        bracketPair5: hex("#2AA198"),
        bracketPair6: hex("#268BD2"),
        indentGuide: hex("#073642"),
        indentGuideActive: hex("#586E75"),
        sidebarBackground: hex("#00252E"),
        sidebarForeground: hex("#93A1A1"),
        sidebarSectionHeader: hex("#001F27"),
        sidebarSelection: hex("#073642"),
        activityBarBackground: hex("#002B36"),
        activityBarForeground: hex("#93A1A1"),
        activityBarSelection: hex("#FDF6E3"),
        tabBarBackground: hex("#002B36"),
        tabActiveBackground: hex("#002B36"),
        tabInactiveBackground: hex("#00212B"),
        tabActiveForeground: hex("#93A1A1"),
        tabInactiveForeground: hex("#586E75"),
        statusBarBackground: hex("#00212B"),
        statusBarForeground: hex("#93A1A1"),
        keyword: hex("#859900"),
        string: hex("#2AA198"),
        number: hex("#D33682"),
        comment: hex("#586E75"),
        function: hex("#268BD2"),
        type: hex("#CB4B16"),
        variable: hex("#B58900")
    )
    
    static let solarizedLight = Theme(
        id: "solarized_light",
        name: "Solarized Light",
        isDark: false,
        editorBackground: hex("#FDF6E3"),
        editorForeground: hex("#657B83"),
        selection: hex("#EEE8D5"),
        cursor: hex("#D30102"),
        lineNumber: hex("#93A1A1"),
        lineNumberActive: hex("#586E75"),
        currentLineHighlight: hex("#EEE8D5"),
        bracketPair1: hex("#859900"),
        bracketPair2: hex("#2AA198"),
        bracketPair3: hex("#268BD2"),
        bracketPair4: hex("#859900"),
        bracketPair5: hex("#2AA198"),
        bracketPair6: hex("#268BD2"),
        indentGuide: hex("#EEE8D5"),
        indentGuideActive: hex("#93A1A1"),
        sidebarBackground: hex("#EEE8D5"),
        sidebarForeground: hex("#586E75"),
        sidebarSectionHeader: hex("#DDD6C1"),
        sidebarSelection: hex("#D3CBB8"),
        activityBarBackground: hex("#DDD6C1"),
        activityBarForeground: hex("#586E75"),
        activityBarSelection: hex("#073642"),
        tabBarBackground: hex("#EEE8D5"),
        tabActiveBackground: hex("#FDF6E3"),
        tabInactiveBackground: hex("#EEE8D5"),
        tabActiveForeground: hex("#073642"),
        tabInactiveForeground: hex("#93A1A1"),
        statusBarBackground: hex("#EEE8D5"),
        statusBarForeground: hex("#586E75"),
        keyword: hex("#859900"),
        string: hex("#2AA198"),
        number: hex("#D33682"),
        comment: hex("#93A1A1"),
        function: hex("#268BD2"),
        type: hex("#CB4B16"),
        variable: hex("#B58900")
    )
    
    static let dracula = Theme(
        id: "dracula",
        name: "Dracula",
        isDark: true,
        editorBackground: hex("#282A36"),
        editorForeground: hex("#F8F8F2"),
        selection: hex("#44475A"),
        cursor: hex("#F8F8F2"),
        lineNumber: hex("#6272A4"),
        lineNumberActive: hex("#F8F8F2"),
        currentLineHighlight: hex("#44475A"),
        bracketPair1: hex("#F8F8F2"),
        bracketPair2: hex("#FF79C6"),
        bracketPair3: hex("#8BE9FD"),
        bracketPair4: hex("#F8F8F2"),
        bracketPair5: hex("#FF79C6"),
        bracketPair6: hex("#8BE9FD"),
        indentGuide: hex("#424450"),
        indentGuideActive: hex("#6272A4"),
        sidebarBackground: hex("#21222C"),
        sidebarForeground: hex("#F8F8F2"),
        sidebarSectionHeader: hex("#191A21"),
        sidebarSelection: hex("#44475A"),
        activityBarBackground: hex("#343746"),
        activityBarForeground: hex("#F8F8F2"),
        activityBarSelection: hex("#F8F8F2"),
        tabBarBackground: hex("#191A21"),
        tabActiveBackground: hex("#282A36"),
        tabInactiveBackground: hex("#21222C"),
        tabActiveForeground: hex("#F8F8F2"),
        tabInactiveForeground: hex("#6272A4"),
        statusBarBackground: hex("#BD93F9"),
        statusBarForeground: hex("#282A36"),
        keyword: hex("#FF79C6"),
        string: hex("#F1FA8C"),
        number: hex("#BD93F9"),
        comment: hex("#6272A4"),
        function: hex("#50FA7B"),
        type: hex("#8BE9FD"),
        variable: hex("#FFB86C")
    )
    
    static let oneDarkPro = Theme(
        id: "one_dark_pro",
        name: "One Dark Pro",
        isDark: true,
        editorBackground: hex("#282C34"),
        editorForeground: hex("#ABB2BF"),
        selection: hex("#3E4451"),
        cursor: hex("#528BFF"),
        lineNumber: hex("#4B5263"),
        lineNumberActive: hex("#ABB2BF"),
        currentLineHighlight: hex("#2C313C"),
        bracketPair1: hex("#C678DD"),
        bracketPair2: hex("#61AFEF"),
        bracketPair3: hex("#E5C07B"),
        bracketPair4: hex("#C678DD"),
        bracketPair5: hex("#61AFEF"),
        bracketPair6: hex("#E5C07B"),
        indentGuide: hex("#3B4048"),
        indentGuideActive: hex("#5C6370"),
        sidebarBackground: hex("#21252B"),
        sidebarForeground: hex("#ABB2BF"),
        sidebarSectionHeader: hex("#282C34"),
        sidebarSelection: hex("#2C313A"),
        activityBarBackground: hex("#282C34"),
        activityBarForeground: hex("#ABB2BF"),
        activityBarSelection: hex("#D7DAE0"),
        tabBarBackground: hex("#21252B"),
        tabActiveBackground: hex("#282C34"),
        tabInactiveBackground: hex("#21252B"),
        tabActiveForeground: hex("#D7DAE0"),
        tabInactiveForeground: hex("#5C6370"),
        statusBarBackground: hex("#21252B"),
        statusBarForeground: hex("#9DA5B4"),
        keyword: hex("#C678DD"),
        string: hex("#98C379"),
        number: hex("#D19A66"),
        comment: hex("#5C6370"),
        function: hex("#61AFEF"),
        type: hex("#E5C07B"),
        variable: hex("#E06C75")
    )
    
    static let nord = Theme(
        id: "nord",
        name: "Nord",
        isDark: true,
        editorBackground: hex("#2E3440"),
        editorForeground: hex("#D8DEE9"),
        selection: hex("#434C5E"),
        cursor: hex("#D8DEE9"),
        lineNumber: hex("#4C566A"),
        lineNumberActive: hex("#D8DEE9"),
        currentLineHighlight: hex("#3B4252"),
        bracketPair1: hex("#EBCB8B"),
        bracketPair2: hex("#A3BE8C"),
        bracketPair3: hex("#81A1C1"),
        bracketPair4: hex("#EBCB8B"),
        bracketPair5: hex("#A3BE8C"),
        bracketPair6: hex("#81A1C1"),
        indentGuide: hex("#434C5E"),
        indentGuideActive: hex("#4C566A"),
        sidebarBackground: hex("#2E3440"),
        sidebarForeground: hex("#D8DEE9"),
        sidebarSectionHeader: hex("#3B4252"),
        sidebarSelection: hex("#3B4252"),
        activityBarBackground: hex("#2E3440"),
        activityBarForeground: hex("#D8DEE9"),
        activityBarSelection: hex("#88C0D0"),
        tabBarBackground: hex("#2E3440"),
        tabActiveBackground: hex("#3B4252"),
        tabInactiveBackground: hex("#2E3440"),
        tabActiveForeground: hex("#D8DEE9"),
        tabInactiveForeground: hex("#4C566A"),
        statusBarBackground: hex("#3B4252"),
        statusBarForeground: hex("#D8DEE9"),
        keyword: hex("#81A1C1"),
        string: hex("#A3BE8C"),
        number: hex("#B48EAD"),
        comment: hex("#616E88"),
        function: hex("#88C0D0"),
        type: hex("#8FBCBB"),
        variable: hex("#D8DEE9")
    )
    
    static let githubDark = Theme(
        id: "github_dark",
        name: "GitHub Dark",
        isDark: true,
        editorBackground: hex("#0D1117"),
        editorForeground: hex("#C9D1D9"),
        selection: hex("#163356"),
        cursor: hex("#58A6FF"),
        lineNumber: hex("#484F58"),
        lineNumberActive: hex("#C9D1D9"),
        currentLineHighlight: hex("#161B22"),
        bracketPair1: hex("#79C0FF"),
        bracketPair2: hex("#D2A8FF"),
        bracketPair3: hex("#FFA657"),
        bracketPair4: hex("#79C0FF"),
        bracketPair5: hex("#D2A8FF"),
        bracketPair6: hex("#FFA657"),
        indentGuide: hex("#21262D"),
        indentGuideActive: hex("#30363D"),
        sidebarBackground: hex("#010409"),
        sidebarForeground: hex("#C9D1D9"),
        sidebarSectionHeader: hex("#161B22"),
        sidebarSelection: hex("#1F2428"),
        activityBarBackground: hex("#0D1117"),
        activityBarForeground: hex("#C9D1D9"),
        activityBarSelection: hex("#C9D1D9"),
        tabBarBackground: hex("#010409"),
        tabActiveBackground: hex("#0D1117"),
        tabInactiveBackground: hex("#010409"),
        tabActiveForeground: hex("#C9D1D9"),
        tabInactiveForeground: hex("#8B949E"),
        statusBarBackground: hex("#0D1117"),
        statusBarForeground: hex("#58A6FF"),
        keyword: hex("#FF7B72"),
        string: hex("#A5D6FF"),
        number: hex("#79C0FF"),
        comment: hex("#8B949E"),
        function: hex("#D2A8FF"),
        type: hex("#79C0FF"),
        variable: hex("#FFA657")
    )
    
    static let githubLight = Theme(
        id: "github_light",
        name: "GitHub Light",
        isDark: false,
        editorBackground: hex("#FFFFFF"),
        editorForeground: hex("#24292F"),
        selection: hex("#B6E3FF"),
        cursor: hex("#0969DA"),
        lineNumber: hex("#8C959F"),
        lineNumberActive: hex("#24292F"),
        currentLineHighlight: hex("#F6F8FA"),
        bracketPair1: hex("#0550AE"),
        bracketPair2: hex("#8250DF"),
        bracketPair3: hex("#953800"),
        bracketPair4: hex("#0550AE"),
        bracketPair5: hex("#8250DF"),
        bracketPair6: hex("#953800"),
        indentGuide: hex("#D0D7DE"),
        indentGuideActive: hex("#8C959F"),
        sidebarBackground: hex("#F6F8FA"),
        sidebarForeground: hex("#24292F"),
        sidebarSectionHeader: hex("#EAEEF2"),
        sidebarSelection: hex("#DDFBE6"),
        activityBarBackground: hex("#F6F8FA"),
        activityBarForeground: hex("#24292F"),
        activityBarSelection: hex("#24292F"),
        tabBarBackground: hex("#F6F8FA"),
        tabActiveBackground: hex("#FFFFFF"),
        tabInactiveBackground: hex("#F6F8FA"),
        tabActiveForeground: hex("#24292F"),
        tabInactiveForeground: hex("#57606A"),
        statusBarBackground: hex("#F6F8FA"),
        statusBarForeground: hex("#0969DA"),
        keyword: hex("#CF222E"),
        string: hex("#0A3069"),
        number: hex("#0550AE"),
        comment: hex("#6E7781"),
        function: hex("#8250DF"),
        type: hex("#0550AE"),
        variable: hex("#953800")
    )
    
    static let cobalt2 = Theme(
        id: "cobalt2",
        name: "Cobalt2",
        isDark: true,
        editorBackground: hex("#193549"),
        editorForeground: hex("#FFFFFF"),
        selection: hex("#0D3A58"),
        cursor: hex("#FEFB00"),
        lineNumber: hex("#3D5F7D"),
        lineNumberActive: hex("#FFFFFF"),
        currentLineHighlight: hex("#1F4662"),
        bracketPair1: hex("#FFC600"),
        bracketPair2: hex("#FF628C"),
        bracketPair3: hex("#80FFBB"),
        bracketPair4: hex("#FFC600"),
        bracketPair5: hex("#FF628C"),
        bracketPair6: hex("#80FFBB"),
        indentGuide: hex("#294B5C"),
        indentGuideActive: hex("#3D5F7D"),
        sidebarBackground: hex("#15232D"),
        sidebarForeground: hex("#FFFFFF"),
        sidebarSectionHeader: hex("#0D1A23"),
        sidebarSelection: hex("#0D3A58"),
        activityBarBackground: hex("#193549"),
        activityBarForeground: hex("#FFFFFF"),
        activityBarSelection: hex("#FFC600"),
        tabBarBackground: hex("#15232D"),
        tabActiveBackground: hex("#193549"),
        tabInactiveBackground: hex("#15232D"),
        tabActiveForeground: hex("#FFFFFF"),
        tabInactiveForeground: hex("#3D5F7D"),
        statusBarBackground: hex("#15232D"),
        statusBarForeground: hex("#FFFFFF"),
        keyword: hex("#FF9D00"),
        string: hex("#A5FF90"),
        number: hex("#FF628C"),
        comment: hex("#0088FF"),
        function: hex("#FFC600"),
        type: hex("#80FFBB"),
        variable: hex("#9EFFFF")
    )
    
    static let ayuDark = Theme(
        id: "ayu_dark",
        name: "Ayu Dark",
        isDark: true,
        editorBackground: hex("#0A0E14"),
        editorForeground: hex("#B3B1AD"),
        selection: hex("#273747"),
        cursor: hex("#E6B450"),
        lineNumber: hex("#3D424D"),
        lineNumberActive: hex("#E6B450"),
        currentLineHighlight: hex("#0D1016"),
        bracketPair1: hex("#FFB454"),
        bracketPair2: hex("#59C2FF"),
        bracketPair3: hex("#AAD94C"),
        bracketPair4: hex("#FFB454"),
        bracketPair5: hex("#59C2FF"),
        bracketPair6: hex("#AAD94C"),
        indentGuide: hex("#1C212B"),
        indentGuideActive: hex("#3D424D"),
        sidebarBackground: hex("#0D1016"),
        sidebarForeground: hex("#B3B1AD"),
        sidebarSectionHeader: hex("#0A0E14"),
        sidebarSelection: hex("#273747"),
        activityBarBackground: hex("#0A0E14"),
        activityBarForeground: hex("#B3B1AD"),
        activityBarSelection: hex("#E6B450"),
        tabBarBackground: hex("#0D1016"),
        tabActiveBackground: hex("#0A0E14"),
        tabInactiveBackground: hex("#0D1016"),
        tabActiveForeground: hex("#B3B1AD"),
        tabInactiveForeground: hex("#3D424D"),
        statusBarBackground: hex("#0D1016"),
        statusBarForeground: hex("#B3B1AD"),
        keyword: hex("#FF8F40"),
        string: hex("#AAD94C"),
        number: hex("#DFBFFF"),
        comment: hex("#626A73"),
        function: hex("#FFB454"),
        type: hex("#59C2FF"),
        variable: hex("#B3B1AD")
    )
    
    static let ayuLight = Theme(
        id: "ayu_light",
        name: "Ayu Light",
        isDark: false,
        editorBackground: hex("#FAFAFA"),
        editorForeground: hex("#5C6166"),
        selection: hex("#D1E4F4"),
        cursor: hex("#FF9940"),
        lineNumber: hex("#9DA2A6"),
        lineNumberActive: hex("#FF9940"),
        currentLineHighlight: hex("#EFF0F1"),
        bracketPair1: hex("#F2AE49"),
        bracketPair2: hex("#399EE6"),
        bracketPair3: hex("#86B300"),
        bracketPair4: hex("#F2AE49"),
        bracketPair5: hex("#399EE6"),
        bracketPair6: hex("#86B300"),
        indentGuide: hex("#E7E8E9"),
        indentGuideActive: hex("#9DA2A6"),
        sidebarBackground: hex("#F0F0F0"),
        sidebarForeground: hex("#5C6166"),
        sidebarSectionHeader: hex("#E7E7E7"),
        sidebarSelection: hex("#D1E4F4"),
        activityBarBackground: hex("#F0F0F0"),
        activityBarForeground: hex("#5C6166"),
        activityBarSelection: hex("#FF9940"),
        tabBarBackground: hex("#F0F0F0"),
        tabActiveBackground: hex("#FAFAFA"),
        tabInactiveBackground: hex("#F0F0F0"),
        tabActiveForeground: hex("#5C6166"),
        tabInactiveForeground: hex("#9DA2A6"),
        statusBarBackground: hex("#F0F0F0"),
        statusBarForeground: hex("#5C6166"),
        keyword: hex("#FA8D3E"),
        string: hex("#86B300"),
        number: hex("#A37ACC"),
        comment: hex("#ABB0B6"),
        function: hex("#F2AE49"),
        type: hex("#399EE6"),
        variable: hex("#5C6166")
    )
    
    static let ayuMirage = Theme(
        id: "ayu_mirage",
        name: "Ayu Mirage",
        isDark: true,
        editorBackground: hex("#1F2430"),
        editorForeground: hex("#CBCCC6"),
        selection: hex("#33415E"),
        cursor: hex("#FFCC66"),
        lineNumber: hex("#707A8C"),
        lineNumberActive: hex("#FFCC66"),
        currentLineHighlight: hex("#232834"),
        bracketPair1: hex("#FFD580"),
        bracketPair2: hex("#73D0FF"),
        bracketPair3: hex("#BAE67E"),
        bracketPair4: hex("#FFD580"),
        bracketPair5: hex("#73D0FF"),
        bracketPair6: hex("#BAE67E"),
        indentGuide: hex("#2D3640"),
        indentGuideActive: hex("#707A8C"),
        sidebarBackground: hex("#232834"),
        sidebarForeground: hex("#CBCCC6"),
        sidebarSectionHeader: hex("#1F2430"),
        sidebarSelection: hex("#33415E"),
        activityBarBackground: hex("#1F2430"),
        activityBarForeground: hex("#CBCCC6"),
        activityBarSelection: hex("#FFCC66"),
        tabBarBackground: hex("#232834"),
        tabActiveBackground: hex("#1F2430"),
        tabInactiveBackground: hex("#232834"),
        tabActiveForeground: hex("#CBCCC6"),
        tabInactiveForeground: hex("#707A8C"),
        statusBarBackground: hex("#232834"),
        statusBarForeground: hex("#CBCCC6"),
        keyword: hex("#FFA759"),
        string: hex("#BAE67E"),
        number: hex("#D4BFFF"),
        comment: hex("#5C6773"),
        function: hex("#FFD580"),
        type: hex("#73D0FF"),
        variable: hex("#CBCCC6")
    )
    
    static let quietLight = Theme(
        id: "quiet_light",
        name: "Quiet Light",
        isDark: false,
        editorBackground: hex("#F5F5F5"),
        editorForeground: hex("#333333"),
        selection: hex("#C9D0D9"),
        cursor: hex("#54494B"),
        lineNumber: hex("#AAAAAA"),
        lineNumberActive: hex("#333333"),
        currentLineHighlight: hex("#E4F6D4"),
        bracketPair1: hex("#7A3E9D"),
        bracketPair2: hex("#448C27"),
        bracketPair3: hex("#4B83CD"),
        bracketPair4: hex("#7A3E9D"),
        bracketPair5: hex("#448C27"),
        bracketPair6: hex("#4B83CD"),
        indentGuide: hex("#E0E0E0"),
        indentGuideActive: hex("#AAAAAA"),
        sidebarBackground: hex("#E7E7E7"),
        sidebarForeground: hex("#333333"),
        sidebarSectionHeader: hex("#DDDDDD"),
        sidebarSelection: hex("#C9D0D9"),
        activityBarBackground: hex("#E7E7E7"),
        activityBarForeground: hex("#333333"),
        activityBarSelection: hex("#333333"),
        tabBarBackground: hex("#E7E7E7"),
        tabActiveBackground: hex("#F5F5F5"),
        tabInactiveBackground: hex("#E7E7E7"),
        tabActiveForeground: hex("#333333"),
        tabInactiveForeground: hex("#AAAAAA"),
        statusBarBackground: hex("#E7E7E7"),
        statusBarForeground: hex("#333333"),
        keyword: hex("#4B83CD"),
        string: hex("#448C27"),
        number: hex("#AB6526"),
        comment: hex("#AAAAAA"),
        function: hex("#7A3E9D"),
        type: hex("#7A3E9D"),
        variable: hex("#333333")
    )
    
    static let red = Theme(
        id: "red",
        name: "Red",
        isDark: true,
        editorBackground: hex("#390000"),
        editorForeground: hex("#F8F8F8"),
        selection: hex("#750000"),
        cursor: hex("#FF0000"),
        lineNumber: hex("#FF6666"),
        lineNumberActive: hex("#FFFFFF"),
        currentLineHighlight: hex("#500000"),
        bracketPair1: hex("#FFFF66"),
        bracketPair2: hex("#AAFFAA"),
        bracketPair3: hex("#AADDFF"),
        bracketPair4: hex("#FFFF66"),
        bracketPair5: hex("#AAFFAA"),
        bracketPair6: hex("#AADDFF"),
        indentGuide: hex("#550000"),
        indentGuideActive: hex("#CC6666"),
        sidebarBackground: hex("#300000"),
        sidebarForeground: hex("#F8F8F8"),
        sidebarSectionHeader: hex("#500000"),
        sidebarSelection: hex("#750000"),
        activityBarBackground: hex("#390000"),
        activityBarForeground: hex("#F8F8F8"),
        activityBarSelection: hex("#FF0000"),
        tabBarBackground: hex("#300000"),
        tabActiveBackground: hex("#390000"),
        tabInactiveBackground: hex("#300000"),
        tabActiveForeground: hex("#FFFFFF"),
        tabInactiveForeground: hex("#CC6666"),
        statusBarBackground: hex("#FF0000"),
        statusBarForeground: hex("#FFFFFF"),
        keyword: hex("#FF6666"),
        string: hex("#FFA0A0"),
        number: hex("#FFD0D0"),
        comment: hex("#CC6666"),
        function: hex("#FFFF66"),
        type: hex("#AAFFAA"),
        variable: hex("#AADDFF")
    )
    
    static let tomorrowNight = Theme(
        id: "tomorrow_night",
        name: "Tomorrow Night",
        isDark: true,
        editorBackground: hex("#1D1F21"),
        editorForeground: hex("#C5C8C6"),
        selection: hex("#373B41"),
        cursor: hex("#AEAFAD"),
        lineNumber: hex("#969896"),
        lineNumberActive: hex("#C5C8C6"),
        currentLineHighlight: hex("#282A2E"),
        bracketPair1: hex("#F0C674"),
        bracketPair2: hex("#B5BD68"),
        bracketPair3: hex("#81A2BE"),
        bracketPair4: hex("#F0C674"),
        bracketPair5: hex("#B5BD68"),
        bracketPair6: hex("#81A2BE"),
        indentGuide: hex("#373B41"),
        indentGuideActive: hex("#969896"),
        sidebarBackground: hex("#1D1F21"),
        sidebarForeground: hex("#C5C8C6"),
        sidebarSectionHeader: hex("#282A2E"),
        sidebarSelection: hex("#373B41"),
        activityBarBackground: hex("#1D1F21"),
        activityBarForeground: hex("#C5C8C6"),
        activityBarSelection: hex("#81A2BE"),
        tabBarBackground: hex("#1D1F21"),
        tabActiveBackground: hex("#282A2E"),
        tabInactiveBackground: hex("#1D1F21"),
        tabActiveForeground: hex("#C5C8C6"),
        tabInactiveForeground: hex("#969896"),
        statusBarBackground: hex("#282A2E"),
        statusBarForeground: hex("#C5C8C6"),
        keyword: hex("#B294BB"),
        string: hex("#B5BD68"),
        number: hex("#DE935F"),
        comment: hex("#969896"),
        function: hex("#81A2BE"),
        type: hex("#F0C674"),
        variable: hex("#CC6666")
    )
    
    static let tomorrowNightBlue = Theme(
        id: "tomorrow_night_blue",
        name: "Tomorrow Night Blue",
        isDark: true,
        editorBackground: hex("#002451"),
        editorForeground: hex("#FFFFFF"),
        selection: hex("#003F8E"),
        cursor: hex("#FFFFFF"),
        lineNumber: hex("#7285B7"),
        lineNumberActive: hex("#FFFFFF"),
        currentLineHighlight: hex("#00346E"),
        bracketPair1: hex("#FFEEAD"),
        bracketPair2: hex("#D1F1A9"),
        bracketPair3: hex("#BBDAFF"),
        bracketPair4: hex("#FFEEAD"),
        bracketPair5: hex("#D1F1A9"),
        bracketPair6: hex("#BBDAFF"),
        indentGuide: hex("#003875"),
        indentGuideActive: hex("#7285B7"),
        sidebarBackground: hex("#001E40"),
        sidebarForeground: hex("#FFFFFF"),
        sidebarSectionHeader: hex("#003875"),
        sidebarSelection: hex("#003F8E"),
        activityBarBackground: hex("#002451"),
        activityBarForeground: hex("#FFFFFF"),
        activityBarSelection: hex("#BBDAFF"),
        tabBarBackground: hex("#001E40"),
        tabActiveBackground: hex("#002451"),
        tabInactiveBackground: hex("#001E40"),
        tabActiveForeground: hex("#FFFFFF"),
        tabInactiveForeground: hex("#7285B7"),
        statusBarBackground: hex("#003875"),
        statusBarForeground: hex("#FFFFFF"),
        keyword: hex("#EBBBFF"),
        string: hex("#D1F1A9"),
        number: hex("#FFC58F"),
        comment: hex("#7285B7"),
        function: hex("#BBDAFF"),
        type: hex("#FFEEAD"),
        variable: hex("#FF9DA4")
    )
    
    static let highContrast = Theme(
        id: "high_contrast",
        name: "High Contrast",
        isDark: true,
        editorBackground: hex("#000000"),
        editorForeground: hex("#FFFFFF"),
        selection: hex("#FFFFFF").opacity(0.3),
        cursor: hex("#FFFFFF"),
        lineNumber: hex("#FFFFFF"),
        lineNumberActive: hex("#FFFFFF"),
        currentLineHighlight: hex("#FFFFFF").opacity(0.1),
        bracketPair1: hex("#FFD700"),
        bracketPair2: hex("#00FF00"),
        bracketPair3: hex("#00BFFF"),
        bracketPair4: hex("#FFD700"),
        bracketPair5: hex("#00FF00"),
        bracketPair6: hex("#00BFFF"),
        indentGuide: hex("#FFFFFF").opacity(0.2),
        indentGuideActive: hex("#FFFFFF").opacity(0.5),
        sidebarBackground: hex("#000000"),
        sidebarForeground: hex("#FFFFFF"),
        sidebarSectionHeader: hex("#000000"),
        sidebarSelection: hex("#FFFFFF").opacity(0.15),
        activityBarBackground: hex("#000000"),
        activityBarForeground: hex("#FFFFFF"),
        activityBarSelection: hex("#FFFFFF"),
        tabBarBackground: hex("#000000"),
        tabActiveBackground: hex("#000000"),
        tabInactiveBackground: hex("#000000"),
        tabActiveForeground: hex("#FFFFFF"),
        tabInactiveForeground: hex("#FFFFFF").opacity(0.6),
        statusBarBackground: hex("#0000AA"),
        statusBarForeground: hex("#FFFFFF"),
        keyword: hex("#569CD6"),
        string: hex("#CE9178"),
        number: hex("#B5CEA8"),
        comment: hex("#7CA668"),
        function: hex("#DCDCAA"),
        type: hex("#4EC9B0"),
        variable: hex("#9CDCFE")
    )
    
    // MARK: - All Themes
    static let allThemes: [Theme] = [
        .darkPlus,
        .lightPlus,
        .monokai,
        .solarizedDark,
        .solarizedLight,
        .dracula,
        .oneDarkPro,
        .nord,
        .githubDark,
        .githubLight,
        .cobalt2,
        .ayuDark,
        .ayuLight,
        .ayuMirage,
        .quietLight,
        .red,
        .tomorrowNight,
        .tomorrowNightBlue,
        .highContrast
    ]
}